language: rust

matrix:
  include:
    - os: linux
      rust: nightly
      env:
      - MATRIX_EVAL="export CXX=g++-6"
      - TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6

    - os: linux
      rust: nightly
      env:
      - MATRIX_EVAL="export CXX=clang++-5.0"
      - TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-5.0
          packages:
          - clang-5.0

    - os: osx
      rust: nightly
      env:
      - TARGET=x86_64-apple-darwin

before_install:
- set -e
- eval "${MATRIX_EVAL}"

script:
  - cargo check --target $TARGET
  - cargo test --target $TARGET

after_script: set +e

cache: cargo

branches:
  only:
  - master

notifications:
  email:
    on_success: never
