language: rust
cache: cargo

matrix:
  include:
    - name: "Linux"
      os: linux
      rust: nightly

    - name: "MacOSX"
      os: osx
      osx_image: xcode10
      rust: nightly

script:
  - rustup component add rust-src
  - cargo install -f xargo
  - cargo check
  - cargo test

notifications:
  email:
    on_success: never
