language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_install: set -e

script:
  - cargo check --target $TARGET
  - cargo test --target $TARGET

after_script: set +e

cache: cargo

notifications:
  email:
    on_success: never