language: rust
cache: cargo

matrix:
  include:
    - os: linux
      rust: stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
            - llvm-5.0-dev

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-6
            - llvm-5.0-dev

    - os: osx
      rust: stable
      env:
        - MATRIX_EVAL="brew install llvm && export LLVM_SYS_50_PREFIX=/usr/local/opt/llvm"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cargo check
  - cargo test

branches:
  only:
    - master

notifications:
  email:
    on_success: never
