[package]
name = "ptx-linker"
version = "0.1.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]

[[bin]]
name = "ptx-linker"
doc = false

[lib]
name = "ptx_linker"

[dependencies]
cty = "0.1"

[dev-dependencies]
difference = "1.0"
tempdir = "0.3"

[badges]
travis-ci = { repository = "denzp/rust-ptx-linker" }