[package]
name = "ptx-linker"
version = "0.5.0"
description = "NVPTX modules linker"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
repository = "https://github.com/denzp/rust-ptx-linker"
readme = "README.md"
license = "MIT"

exclude = [
    "tests/**/*",
]

[[bin]]
name = "ptx-linker"
doc = false
path = "src/application/main.rs"

[lib]
name = "ptx_linker"

[dependencies]
llvm-sys = "50"
log = "0.3"
fern = "0.4"
colored = "1.5"
error-chain = "0.10"
ar = "0.5"
clap = { version = "2.31", features = ["yaml", "suggestions", "color"] }

[dev-dependencies]
difference = "1.0"
tempdir = "0.3"

[build-dependencies]
cc = "1.0"

[badges]
travis-ci = { repository = "denzp/rust-ptx-linker", branch = "master" }